### ISSUE TITLE
是否考虑建立一个标号机制？

### ISSUE THREAD

**Issue by IMBlues** [TencentBlueKing/best-practices#8]
类似 PEP 规则，最佳实践可以有一个标号 （例如 PBP？）

例子：

#### PBP-1 不要在代码中出现魔术数字

不要在代码中出现 [Magic Number](https://en.wikipedia.org/wiki/Magic_number_(programming))，常量应该使用 Enum 模块来替代。

```python
# BAD
if cluster_type == 1:
    pass


# GOOD
from enum import Enum

Class BCSType(Enum):
    K8S = 1
    Mesos = 2

if cluster_type == BCSType.K8S.value:
    pass
```

好处是，每一个建议都可以有一个简单的索引方式，在 code review 中可以通过 `PBP-X` 的方式向其他人建议，更容易传播和记忆。

**Comment by yiqiwang-17** [comment]
python\django\drf各以一个标号开头作为编码记录，如PEP-001\PEP-101\PEP-201。

**Comment by IMBlues** [comment]
# Blueking Best Practice - BBP


标号形如 

```
BBP-0001
```

- 其中 `BBP-` 作为前缀，和其他任何标号系统区分
- `001` 代表具体 最佳实践序号，作为某一个最佳实践的唯一标识。

同时为了保证标号有一定的记忆度和扩展性，序号部分我们又分为两个部分：

```
00                  001
领域序号             领域内序号
```

什么是领域？这里的领域可以理解为一种技术标签，它代表了某一类技术领域，例如 Python/Golang 这样的语言层面，也可以是 Redis/MySQL 这类的常用的存储组件层面。领域序号默认预留了两位数字，最多支持100种领域划分。为了保证前期整体标号的短小，领域序号可以简略掉前面多余的 "0"，例如 `01` 可缩减为 `1`。

目前已规划的领域：
| 序号 | 领域 |
| ---- | ---- |
| Python | 00 |
| Golang | 01 |
| MySQL | 02 |
| Redis | 03 |

领域内序号比较好理解，就是某一个领域中的最佳实践，默认按照合入的时间依次累加。

### 领域如何划分？

## BBP-0000 有关最佳实践的最佳实践

BBP-0000 是一个特殊的最佳实践，用来阐述该最佳实践的用法和维护办法。

### 如何使用标号？

标号的意义在于给已经形成沉淀的最佳实践**用于追溯的索引**，一个便于记忆与传播的短名字。常见的场景如下：
- MR/PR 讨论时，可以直接引用标号
- 在代码注释中阐述采用当前方案的原因

### 标号确立后如何更新？

当某一个实践的标号确定后，不建议对其中内容做大幅度的更新，除非含有事实性错误。

### 过期

对于一些实践内容因为某些技术版本的更新而发生过期时，应当将当前实践特殊标记为“过期”，在醒目的位置展示过期原因，如有必要可以添加一条新的实践用于替代当前实践的作用，标号累加，而不是删除当前标号。
